Repository ProjectEvergreen/wcc, pull requests merged in 2025-01, with the labels that each got.

#178 enhancement/rework of DOM shim (using parse5) to allow for element properties in the future
  src/dom-shim.js
  src/wcc.js
  test/cases/create-document-fragment/create-document-fragment.spec.js
  test/cases/create-document-fragment/src/index.js
  test/cases/full-document-component/full-document-component.spec.js
  test/cases/full-document-component/src/index.js
  test/cases/serializable-shadow-roots/serializable-shadow-roots.spec.js
  test/cases/serializable-shadow-roots/src/components/serializable-non-ssr-component.js
  test/cases/serializable-shadow-roots/src/components/serializable-ssr-component.js
  test/cases/serializable-shadow-roots/src/components/unserializable-non-ssr-component.js
  test/cases/serializable-shadow-roots/src/components/unserializable-ssr-component.js
  test/cases/serializable-shadow-roots/src/index.js
  test/cases/shadowrootmode/shadowrootmode.spec.js
  test/cases/shadowrootmode/src/components/closed-shadow-component.js
  test/cases/shadowrootmode/src/components/open-shadow-component.js
  test/cases/shadowrootmode/src/index.js
Labels: bug, enhancement, 0.16.0

#184 bug/issue 170 handle support for element properties
  src/dom-shim.js
  src/wcc.js
  test/cases/element-props/element-props.spec.js
  test/cases/element-props/src/components/prop-passer.js
  test/cases/element-props/src/components/prop-receiver.js
  test/cases/element-props/src/index.js
  test/cases/element-props/src/renderer.js
  test/cases/set-attribute/set-attribute.spec.js
  test/cases/set-attribute/src/index.js
Labels: bug

#183 enhancement/upgrade parse5 to v7
  package-lock.json
  package.json
Labels: enhancement, 0.16.0

#185 docs/document usage of setting `shadowRoot.innerHTML`
  docs/pages/docs.md
Labels: documentation
